* Notes about [[https://asc.llnl.gov/CORAL-benchmarks/][CORAL]] benchmak codes : 
| Benchmark   | reference |Lines of code | parallelism  | Lang | Notes     | on MPI | on SMPI | about SMPI test |
|-------------+-----------+--------------+--------------+------+-----------+--------+---------+-----------------|
| [[https://asc.llnl.gov/CORAL-benchmarks/Throughput/amg20130624.tgz][amg2013]] | [[https://asc.llnl.gov/CORAL-benchmarks/Summaries/AMG2013_Summary_v2.3.pdf][ref]] | 75,000 | MPI-OPENMP | C | Work with some adjustments | YES | NO | deadlock |
| [[https://asc.llnl.gov/CORAL-benchmarks/Skeleton/HACC_IO.tar.gz][HACCIO]] | [[https://asc.llnl.gov/CORAL-benchmarks/Summaries/HACC_IO_Summary_v1.0.pdf][ref]] | 2,000 | MPI | C++ | work but shows warrnings | YES | NO | Building issue due to using smpicxx instead of mpicxx |
| [[https://asc.llnl.gov/CORAL-benchmarks/Datacentric/KMI_HASH_CORAL.tar.gz][KMI_HASH]] | [[https://asc.llnl.gov/CORAL-benchmarks/Summaries/KMI_Summary_v1.1.pdf][ref]] | / | MPI | C | work but shows warnings | YES | NO | Building issue |

* Notes about [[http://www.nersc.gov/users/computational-systems/cori/nersc-8-procurement/trinity-nersc-8-rfp/nersc-8-trinity-benchmarks/][trinity-nersc]] benchmak codes : 
| Benchmark   | reference |Lines of code | parallelism  | Lang | Notes     | on MPI | on SMPI | about SMPI test |
|-------------+-----------+--------------+--------------+------+-----------+--------+---------+-----------------|
| [[http://www.nersc.gov/assets/Trinity--NERSC-8-RFP/Benchmarks/Jan9/smb1.0-1.tar][SMB]] | [[http://www.nersc.gov/users/computational-systems/cori/nersc-8-procurement/trinity-nersc-8-rfp/nersc-8-trinity-benchmarks/smb/][ref]] | unknown | MPI | C | work well | YES | YES | slow |
| [[http://www.nersc.gov/assets/Trinity--NERSC-8-RFP/Benchmarks/June28/psnap-1.2June28.tar][psnap]] | [[http://www.nersc.gov/users/computational-systems/cori/nersc-8-procurement/trinity-nersc-8-rfp/nersc-8-trinity-benchmarks/psnap/][ref]] | unknown | MPI | C | work well | YES | YES | deadlock |
| [[http://www.nersc.gov/assets/Trinity--NERSC-8-RFP/Benchmarks/Jan9/ziatest.tar][ziatest]] | [[http://www.nersc.gov/users/computational-systems/cori/nersc-8-procurement/trinity-nersc-8-rfp/nersc-8-trinity-benchmarks/ziatest/][ref]] | unknown | MPI | C | work well | YES 3 args are requested | NO | it's required by MPI-2, this is currently not supported by SMPI |
| [[http://www.nersc.gov/assets/Trinity--NERSC-8-RFP/Benchmarks/Mar29/mdtest-1.8.4.tar][mdtest]] | [[http://www.nersc.gov/users/computational-systems/cori/nersc-8-procurement/trinity-nersc-8-rfp/nersc-8-trinity-benchmarks/mdtest/][ref]] | unknown | MPI | C | work well | YES | NO | deadlock |
| [[http://www.nersc.gov/assets/Trinity--NERSC-8-RFP/Benchmarks/July5/mpimemu-1.0-rc6July5.tar][mpimemu]] | [[http://www.nersc.gov/users/computational-systems/cori/nersc-8-procurement/trinity-nersc-8-rfp/nersc-8-trinity-benchmarks/mpimemu/][ref]] | unknown | MPI | C | work well ./configure && make | YES | NO | / |
| [[http://www.nersc.gov/assets/Trinity--NERSC-8-RFP/Benchmarks/July12/osu-micro-benchmarks-3.8-July12.tar][OMB_MPI Tests]] | [[http://www.nersc.gov/users/computational-systems/cori/nersc-8-procurement/trinity-nersc-8-rfp/nersc-8-trinity-benchmarks/omb-mpi-tests/][ref]] | unknown | MPI | C | MPI work | YES | NO | / |

* Notes about [[https://mantevo.org/download/][mantevo]] benchmak codes : 
| Benchmark   | reference |Lines of code | parallelism  | Lang | Notes     | on MPI | on SMPI | about SMPI test |
|-------------+-----------+--------------+--------------+------+-----------+--------+---------+-----------------|
| [[http://mantevo.org/downloads/miniXyce_1.0.html][MiniXcye]] | NONE | unknown | MPI | C++ | Work but shows warnings | YES | NO |
| [[http://mantevo.org/downloads/miniSMAC2D_2.0.html][MiniSMAC2D]] | NONE | unknown | MPI, OPENMP | FORTRAN | Some adjustment should be done to get build the code, although the code show errors and warnings | YES but the localization of input file should be changed | YES | but it got "killing simulation" |


** [[https://asc.llnl.gov/CORAL-benchmarks/Summaries/AMG2013_Summary_v2.3.pdf][amg2013]]
*** brief description : 
AMG is a parallel algebraic multigrid solver for linear systems arising from problems on unstructured grids.
#+BEGIN_SRC sh
     wget "https://asc.llnl.gov/CORAL-benchmarks/Throughput/amg20130624.tgz"
     tar -xvf *.tgz 
     rm -rf *.tgz
     cp -f src/AMG2013/*.txt src/AMG2013/*.xml AMG2013/test/
     cp -f src/AMG2013/*.include AMG2013/
     cd AMG2013/
     make
     smpirun -np 8 -hostfile ./cluster_hostfile.txt -platform ./cluster_crossbar.xml ./amg2013 -pooldist 1 -r 12 12 12
#+END_SRC


** [[https://asc.llnl.gov/CORAL-benchmarks/Summaries/HACC_IO_Summary_v1.0.pdf][HACC_IO]]
*** brief description : 
The HACC I/O benchmark capture the I/O patterns of the HACC simulation code.
#+BEGIN_SRC sh
     wget "https://asc.llnl.gov/CORAL-benchmarks/Skeleton/HACC_IO.tar.gz"
     tar -xvf *.tgz 
     rm -rf *.tgz
     cp -f src/HACC_IO_KERNEL/* HACC_IO_KERNEL/
     cd HACC_IO_KERNEL/
     make
     smpirun -np 8 -hostfile ./cluster_hostfile.txt -platform ./cluster_crossbar.xml ./HACC_IO 
#+END_SRC

** [[https://asc.llnl.gov/CORAL-benchmarks/Summaries/KMI_Summary_v1.1.pdf][KMI_HASH]]
*** brief description : 
KMI_HASH evaluate the performance of the architecture integer operations, specifically for hashing, and for memory-intensive genomics applications. 
#+BEGIN_SRC sh
     wget "https://asc.llnl.gov/CORAL-benchmarks/Datacentric/KMI_HASH_CORAL.tar.gz"
     tar -xvf *.tgz 
     rm -rf *.tgz
     cp -f src/kmi_hash/* kmi_hash/tests/
     cd kmi_hash/tests/
     make
     smpirun -np 8 -hostfile ./cluster_hostfile.txt -platform ./cluster_crossbar.xml ./kmi_hash 
#+END_SRC

** [[http://www.nersc.gov/users/computational-systems/cori/nersc-8-procurement/trinity-nersc-8-rfp/nersc-8-trinity-benchmarks/smb/][SMB]]
*** brief description : 
#+BEGIN_SRC sh
     wget "http://www.nersc.gov/assets/Trinity--NERSC-8-RFP/Benchmarks/Jan9/smb1.0-1.tar"
     tar -xvf *.tar 
     rm -rf *.tar
     cp -f src/smb/mpi_overhead/* smb_1.0-1/src/mpi_overhead/
     cd smb_1.0-1/src/mpi_overhead/
#+END_SRC

** [[http://www.nersc.gov/users/computational-systems/cori/nersc-8-procurement/trinity-nersc-8-rfp/nersc-8-trinity-benchmarks/psnap/][psnap]]
*** brief description : 
#+BEGIN_SRC sh
     mkdir psnap
     cd psnap
     wget "http://www.nersc.gov/assets/Trinity--NERSC-8-RFP/Benchmarks/June28/psnap-1.2June28.tar"
     tar -xvf *.tar 
     rm -rf *.tar
     cp -f ../src/psnap/* psnap/
     make
     smpirun -np 6 -hostfile ./cluster_hostfile.txt -platform ./cluster_crossbar.xml ./psnap
#+END_SRC

** [[http://www.nersc.gov/users/computational-systems/cori/nersc-8-procurement/trinity-nersc-8-rfp/nersc-8-trinity-benchmarks/ziatest/][ziatest]]
*** brief description : 
#+BEGIN_SRC sh
     mkdir ziatest
     cd ziatest
     wget "http://www.nersc.gov/assets/Trinity--NERSC-8-RFP/Benchmarks/Jan9/ziatest.tar"
     tar -xvf *.tar 
     rm -rf *.tar
     cp -f ../src/ziatest/* ./
     smpirun -np 8 -hostfile ./cluster_hostfile.txt -platform ./cluster_crossbar.xml ./ziaprobe 4 4 2
 #+END_SRC

** [[http://www.nersc.gov/users/computational-systems/cori/nersc-8-procurement/trinity-nersc-8-rfp/nersc-8-trinity-benchmarks/mdtest/][mdtest]]
*** brief description : 
it's seems that is work here.
#+BEGIN_SRC sh
     wget "http://www.nersc.gov/assets/Trinity--NERSC-8-RFP/Benchmarks/Mar29/mdtest-1.8.4.tar"
     tar -xvf *.tar 
     rm -rf *.tar
     cp -f src/mdtest/* mdtest-1.8.4/
     cd mdtest-1.8.4/
     make
     smpirun -np 2 -hostfile ./cluster_hostfile.txt -platform ./cluster_crossbar.xml ./mdtest --cfg=smpi/host-speed:100 --cfg=smpi/privatization:yes
 #+END_SRC

** [[http://www.nersc.gov/users/computational-systems/cori/nersc-8-procurement/trinity-nersc-8-rfp/nersc-8-trinity-benchmarks/mpimemu/][mpimemu]]
*** brief description : 
#+BEGIN_SRC sh
     wget "http://www.nersc.gov/assets/Trinity--NERSC-8-RFP/Benchmarks/July5/mpimemu-1.0-rc6July5.tar"
     tar -xvf *.tar 
     rm -rf *.tar
     cp -f src/mpimemu/* mpimemu-1.0-rc6July5/
     cd mpimemu-1.0-rc6July5/
     source util/env-setup-bash
     ./configure
     cd src/
 #+END_SRC

** MiniXcye
*** brief description : 
#+BEGIN_SRC sh
     wget "http://mantevo.org/downloads/miniXyce_1.0.html"
     tar -xvf *.tar 
     rm -rf *.tar 
     cd miniXyce_1.0/miniXyce_ref/
     make
 #+END_SRC

** [[http://www.nersc.gov/users/computational-systems/cori/nersc-8-procurement/trinity-nersc-8-rfp/nersc-8-trinity-benchmarks/omb-mpi-tests/][OMB_MPI]]
*** brief description : 
it's seems that is work here.
#+BEGIN_SRC sh
     wget "http://www.nersc.gov/assets/Trinity--NERSC-8-RFP/Benchmarks/July12/osu-micro-benchmarks-3.8-July12.tar"
     tar -xvf *.tar 
     rm -rf *.tar
     cp -f src/OMB_MPI/configure osu-micro-benchmarks-3.8-July12/
     cp -f src/OMB_MPI/* osu-micro-benchmarks-3.8-July12/mpi/pt2pt
     cd osu-micro-benchmarks-3.8-July12/
     ./configure
 #+END_SRC

** [[http://mantevo.org/downloads/miniSMAC2D_2.0.html][miniSMAC2D]]
*** brief description : 
#+BEGIN_SRC sh
     wget "http://mantevo.org/downloads/miniSMAC2D_2.0.html"
     tar -xvf *.tgz 
     rm -rf *.tgz;
     mkdir data;
     cd data
     tar -xvf *.tgz 
     rm -rf *.tgz
     cd ..
     cp -r data/ miniSMAC2D_2.0/
     cd miniSMAC2D_2.0/
     make 
     smpirun -np 6 -hostfile ./cluster_hostfile.txt -platform ./cluster_crossbar.xml ./smac2d_mpi_and_threads_with_AVX
#+END_SRC

