*** [[http://www.nersc.gov/users/computational-systems/cori/nersc-8-procurement/trinity-nersc-8-rfp/nersc-8-trinity-benchmarks/smb/][SMB]]
**** Brief description  
It include two benchmarks :  
- The msg_rate test measures the sustained MPI message rate using a communication pattern found in many real applications.
- The mpi_overhead test uses a post-work-wait method using MPI non-blocking send and receive calls to measure the user level overhead of the respective MPI calls.
**** Build and run  
- mpi_overhead : 
hostfile note found if one use ./run_script.
Or Very slow (Running no stop) if one use the standart runing command. 
#+BEGIN_SRC sh :tangle bin/SMB.sh
  export SIMGRID_PATH="${SIMGRID_PATH:=~/simgrid}"
  export LD_LIBRARY_PATH=$SIMGRID_PATH/build/lib:$SIMGRID_PATH/lib:$LD_LIBRARY_PATH
  export PATH=$SIMGRID_PATH/build/bin:$SIMGRID_PATH/bin:$PATH
     echo "Clean up the place" 
     sh -xe
     rm -rf Benchmarks/smb
     mkdir -p Benchmarks
     cd Benchmarks
     echo "Download the source code"
     test -e smb-source.tgz || curl -o smb-source.tgz -Lk http://www.nersc.gov/assets/Trinity--NERSC-8-RFP/Benchmarks/Jan9/smb1.0-1.tar

     echo "Unpack the code"
     mkdir smb && tar -xvf smb-source.tgz -C smb --strip-components 1

     echo "Install the modified sources"
     cp -f ../src/smb/mpi_overhead/* smb/src/mpi_overhead/
     cp -f ../src/common/* smb/src/mpi_overhead/
     cd smb/src/mpi_overhead/


     echo "Compile it"
     make

     echo "Run it"
     ./run_script 
#+END_SRC

- msg_rate :
Building issue.
     echo "Clean up the place" 
     sh -xe
     rm -rf Benchmarks/smb
     mkdir -p Benchmarks
     cd Benchmarks
     echo "Download the source code"
     test -e smb-source.tgz || curl -o smb-source.tgz -Lk http://www.nersc.gov/assets/Trinity--NERSC-8-RFP/Benchmarks/Jan9/smb1.0-1.tar

     echo "Unpack the code"
     mkdir smb && tar -xvf smb-source.tgz -C smb --strip-components 1

     echo "Install the modified sources"
     cp -f ../src/smb/msgrate/* smb/src/msgrate/
     cp -f ../src/common/* smb/src/msgrate/
     cd smb/src/msgrate/
#+END_SRC

*** [[http://www.nersc.gov/users/computational-systems/cori/nersc-8-procurement/trinity-nersc-8-rfp/nersc-8-trinity-benchmarks/psnap/][PSNAP]]
**** Brief description 
PSNAP (PAL System Noise Activity Program) consists of a spin loop that is calibrated to take a given amount of time (typically 1 ms). This loop is repeated for a number of iterations.
**** Build and run  
#+BEGIN_SRC sh :tangle bin/PSNAP.sh
  export SIMGRID_PATH="${SIMGRID_PATH:=~/simgrid}"
  export LD_LIBRARY_PATH=$SIMGRID_PATH/build/lib:$SIMGRID_PATH/lib:$LD_LIBRARY_PATH
  export PATH=$SIMGRID_PATH/build/bin:$SIMGRID_PATH/bin:$PATH
     echo "Clean up the place" 
     sh -xe
     rm -rf Benchmarks/mdtest
     mkdir -p Benchmarks/
     cd Benchmarks
     echo "Download the source code"
     test -e psnap-source.tgz || curl -o psnap-source.tgz -Lk http://www.nersc.gov/assets/Trinity--NERSC-8-RFP/Benchmarks/June28/psnap-1.2June28.tar

     echo "Unpack the code"
     mkdir psnap && tar -xvf psnap-source.tgz -C psnap
 
     echo "Install the modified sources"
     cd psnap
     cp -f ../../src/Trinity-Nersc/psnap/* ./
     cp -f ../../src/common/* ./

     echo "Compile it"
     make

     echo "Run it"
     smpirun -np 4 -hostfile ./cluster_hostfile.txt -platform ./cluster_crossbar.xml --cfg=smpi/host-speed:100 ./psnap
#+END_SRC

*** [[http://www.nersc.gov/users/computational-systems/cori/nersc-8-procurement/trinity-nersc-8-rfp/nersc-8-trinity-benchmarks/ziatest/][ZiaTest]]
**** Brief description 
It executes a new proposed standard benchmark method for MPI startup that is intended to provide a realistic assessment of
both launch and wireup requirements. Accordingly, it exercises both the launch system of the environment and the interconnect subsystem in a specified pattern.
**** Build and run 
To run the code one has to give 3 args as inputs.
It's required by MPI-2, this is currently not supported by SMPI.
#+BEGIN_SRC sh :tangle bin/ZiaTest.sh
  export SIMGRID_PATH="${SIMGRID_PATH:=~/simgrid}"
  export LD_LIBRARY_PATH=$SIMGRID_PATH/build/lib:$SIMGRID_PATH/lib:$LD_LIBRARY_PATH
  export PATH=$SIMGRID_PATH/build/bin:$SIMGRID_PATH/bin:$PATH
     echo "Clean up the place" 
     sh -xe
     rm -rf Benchmarks/ziatest
     mkdir -p Benchmarks/ziatest
     cd Benchmarks
     echo "Download the source code"
     test -e ziatest-source.tgz || curl -o ziatest-source.tgz -Lk http://www.nersc.gov/assets/Trinity--NERSC-8-RFP/Benchmarks/Jan9/ziatest.tar

     echo "Unpack the code"
     cd ziatest
     tar -xvf ../ziatest-source.tgz

     echo "Install the modified sources"
     cp -f ../../src/Trinity-Nersc/ziatest/* ./
     cp -f ../../src/common/* ./

     echo "Compile it"
     make 

     echo "Run it"
     smpirun -np 8 -hostfile ./cluster_hostfile.txt -platform ./cluster_crossbar.xml "--cfg=smpi/host-speed:100 ./ziaprobe 4 4 2 
 #+END_SRC

 #+RESULTS:

*** [[http://www.nersc.gov/users/computational-systems/cori/nersc-8-procurement/trinity-nersc-8-rfp/nersc-8-trinity-benchmarks/mdtest/][MDTest]]
**** Brief description 
mdtest is a program that measures performance of various metadata operations. It uses MPI to coordinate the operations and to collect the results.   
The code is composed of one C file, mdtest.c. 
**** Build and run    
The execution should done with 2 proc.
#+BEGIN_SRC sh :tangle bin/MDTest.sh
     export SIMGRID_PATH="${SIMGRID_PATH:=~/simgrid}"
     export LD_LIBRARY_PATH=$SIMGRID_PATH/build/lib:$SIMGRID_PATH/lib:$LD_LIBRARY_PATH
     export PATH=$SIMGRID_PATH/build/bin:$SIMGRID_PATH/bin:$PATH

     echo "Clean up the place" 
     set -exu
     rm -rf Benchmarks/mdtest
     mkdir Benchmarks || true
     cd Benchmarks
     echo "Download the source"
     test -e mdtest-source.tgz || curl -o mdtest-source.tgz -Lk http://www.nersc.gov/assets/Trinity--NERSC-8-RFP/Benchmarks/Mar29/mdtest-1.8.4.tar

     echo "Unpack the code"
     mkdir mdtest && tar -xvf mdtest-source.tgz -C mdtest --strip-components 1
 
     echo "Install the modified sources"
     cd mdtest
     cp -f ../../src/Trinity-Nersc/mdtest/* ./
     cp -f ../../src/common/* ./

     echo "Compile it"
     make

     echo "Run it"
     smpirun -np 2 -hostfile ./cluster_hostfile.txt -platform ./cluster_crossbar.xml ./mdtest --cfg=smpi/host-speed:100 --cfg=smpi/privatization:yes
 #+END_SRC

*** [[http://www.nersc.gov/users/computational-systems/cori/nersc-8-procurement/trinity-nersc-8-rfp/nersc-8-trinity-benchmarks/stream/][Stream]]
**** Brief description 
STREAM is a simple, synthetic benchmark designed to measure sustainable memory bandwidth (in MB/s) and a corresponding computation rate for four simple vector kernels.
**** Build and run 
#+BEGIN_SRC sh :tangle bin/stream.sh
     export SIMGRID_PATH="${SIMGRID_PATH:=~/simgrid}"
     export LD_LIBRARY_PATH=$SIMGRID_PATH/build/lib:$SIMGRID_PATH/lib:$LD_LIBRARY_PATH
     export PATH=$SIMGRID_PATH/build/bin:$SIMGRID_PATH/bin:$PATH

     echo "Clean up the place" 
     set -exu
     rm -rf Benchmarks/steam
     mkdir -p Benchmarks/stream || true
     cd Benchmarks
     echo "Download the source"
     test -e stream-source.tgz || curl -o stream-source.tgz -Lk http://www.nersc.gov/assets/Trinity--NERSC-8-RFP/Benchmarks/Jan9/stream.tar

     echo "Unpack the code"
     tar -xvf stream-source.tgz -C stream
 
     echo "Install the modified sources"
     pwd
     cp -f ../src/Trinity-Nersc/stream/* stream/
     cp -f ../src/common/* stream/
     cd stream

     echo "Compile it"
     make

     echo "Run it"
     smpirun -np 4 -hostfile ./cluster_hostfile.txt -platform ./cluster_crossbar.xml ./stream_c.exe
 #+END_SRC

*** [[http://www.nersc.gov/users/computational-systems/cori/nersc-8-procurement/trinity-nersc-8-rfp/nersc-8-trinity-benchmarks/mpimemu/][MPIMemu]]
**** Brief description  
The code is a simple tool that helps approximate MPI library memory usage as a function of scale.  It takes samples of /proc/meminfo (node level)
 and /proc/self/status (process level) and outputs the min, max and avg values for a specified period of time.
**** Build and run
#+BEGIN_SRC sh
     echo "Clean up the place" 
     sh -xe
     rm -rf Benchmarks/mpimemu
     mkdir -p Benchmarks/
     cd Benchmarks
     echo "Download the source code"
     test -e mpimemu-source.tar.gz || curl -o mpimemu-source.tar.gz -Lk http://www.nersc.gov/assets/Trinity--NERSC-8-RFP/Benchmarks/July5/mpimemu-1.0-rc6July5.tar

     echo "Unpack the code"
     mkdir mpimemu && tar -xvf mpimemu-source.tar.gz -C mpimemu --strip-components 1

     echo "Install the modified sources"
     cp -f ../src/mpimemu/configure mpimemu/
     cp -f ../src/common/* mpimemu/src/

     echo "Configure it"
     cd mpimemu-1.0-rc6July5/
     ./configure

     echo "Compile it"
     make 
     cd src/

     echo "Run it"
 #+END_SRC

*** [[http://www.nersc.gov/users/computational-systems/cori/nersc-8-procurement/trinity-nersc-8-rfp/nersc-8-trinity-benchmarks/omb-mpi-tests/][OMB_MPI]]
**** Brief description 
The Ohio MicroBenchmark suite is a collection of independent MPI message passing performance microbenchmarks developed and written at The Ohio State University.
It includes traditional benchmarks and performance measures such as latency, bandwidth and host overhead and can be used for both traditional and GPU-enhanced nodes.
**** Build and run  
#+BEGIN_SRC sh
     echo "Clean up the place" 
     sh -xe
     rm -rf Benchmarks/OMB_MPI
     mkdir -p Benchmarks/
     cd Benchmarks
     echo "Download the source code"
     test -e OMB_MPI-source.tar.gz || curl -o OMB_MPI-source.tar.gz -Lk http://www.nersc.gov/assets/Trinity--NERSC-8-RFP/Benchmarks/July12/osu-micro-benchmarks-3.8-July12.tar

     echo "Unpack the code"
     mkdir OMB_MPI && tar -xvf OMB_MPI-source.tar.gz -C OMB_MPI --strip-components 1

     cd OMB_MPI/
     ./configure

     echo "Install the modified sources"
     cp -f ../../src/Trinity-Nersc/OMB_MPI/mpi/pt2pt/* ./mpi/pt2pt
     cp -f ../../src/common/* ./mpi/pt2pt
     
     echo "Compile it"
     make 

     echo "Run osu_bibw"
     smpirun -np 2 -hostfile ./cluster_hostfile.txt -platform ./cluster_crossbar.xml --cfg=smpi/host-speed:100 --cfg=smpi/privatization:yes ./osu_bibw
     
     echo "Run osu_bw"
     smpirun -np 2 -hostfile ./cluster_hostfile.txt -platform ./cluster_crossbar.xml --cfg=smpi/host-speed:100 --cfg=smpi/privatization:yes ./osu_bw
     
     echo "Run osu_mbw_mr"
     smpirun -np 2 -hostfile ./cluster_hostfile.txt -platform ./cluster_crossbar.xml --cfg=smpi/host-speed:100 --cfg=smpi/privatization:yes ./osu_mbw_mr
     
     echo "Run osu_multi_lat"
     smpirun -np 2 -hostfile ./cluster_hostfile.txt -platform ./cluster_crossbar.xml --cfg=smpi/host-speed:100 --cfg=smpi/privatization:yes ./osu_multi_lat
    
     echo "Run osu_latency"
     smpirun -np 2 -hostfile ./cluster_hostfile.txt -platform ./cluster_crossbar.xml --cfg=smpi/host-speed:100 --cfg=smpi/privatization:yes ./osu_latency
 #+END_SRC

*** [[http://www.nersc.gov/users/computational-systems/cori/nersc-8-procurement/trinity-nersc-8-rfp/nersc-8-trinity-benchmarks/gtc/][GTC]]
**** Brief description  
GTC is used for Gyrokinetic Particle Simulation of Turbulent Transport in Burning Plasmas.
**** Build and run  
#+BEGIN_SRC sh
     echo "Clean up the place" 
     sh -xe
     rm -rf Benchmarks/GTC
     mkdir -p Benchmarks/
     cd Benchmarks

     echo "Download the source code"
     test -e GTC-source.tar || curl -o GTC-source.tar -Lk http://www.nersc.gov/assets/Trinity--NERSC-8-RFP/Benchmarks/May31/TrN8GTCMay30.tar

     echo "Unpack the code"
     mkdir GTC && tar -xvf GTC-source.tar -C GTC --strip-components 1

     echo "Install the modified sources"
     cp ../src/GTC/* GTC/source/
     cp -f ../src/common/* GTC/source/

     echo "Compile it"
     cd GTC/source/
     make 

     echo "Run it"
#+END_SRC

*** [[http://www.nersc.gov/users/computational-systems/cori/nersc-8-procurement/trinity-nersc-8-rfp/nersc-8-trinity-benchmarks/minife/][MiniFE]]
**** Brief description  
FE is a Finite Element mini-application which implements a couple of kernels representative of implicit finite-element applications. 
It assembles a sparse linear-system from the steady-state conduction equation on a brick-shaped problem domain of linear 8-node hex elements.
**** Build and run  
#+BEGIN_SRC sh
     echo "Clean up the place" 
     sh -xe
     rm -rf Benchmarks/MiniFE
     mkdir -p Benchmarks/
     cd Benchmarks
     echo "Download the source code"
     test -e MiniFE-source.tar || curl -o MiniFE-source.tar -Lk http://www.nersc.gov/assets/Trinity--NERSC-8-RFP/Benchmarks/Feb22/MiniFE_ref_1.4b.tar
          
     echo "Unpack the code"
     mkdir MiniFE && tar -xvf MiniFE-source.tar -C MiniFE --strip-components 1
 
     echo "Install the modified sources"
     cp -f ../src/MiniFE/* MiniFE/
     cp -f ../src/common/* MiniFE/
     cd MiniFE/

     echo "Compile it"
     make

     echo "Run it"
#+END_SRC

* Emacs settings
# Local Variables:
# eval:    (org-babel-do-load-languages 'org-babel-load-languages '( (shell . t) (R . t) (perl . t) (ditaa . t) ))
# eval:    (setq org-confirm-babel-evaluate nil)
# eval:    (setq org-alphabetical-lists t)
# eval:    (setq org-src-fontify-natively t)
# eval:    (add-hook 'org-babel-after-execute-hook 'org-display-inline-images) 
# eval:    (add-hook 'org-mode-hook 'org-display-inline-images)
# eval:    (add-hook 'org-mode-hook 'org-babel-result-hide-all)
# eval:    (setq org-babel-default-header-args:R '((:session . "org-R")))
# eval:    (setq org-export-babel-evaluate nil)
# eval:    (setq ispell-local-dictionary "american")
# eval:    (setq org-export-latex-table-caption-above nil)
# eval:    (eval (flyspell-mode t))
# End:
