#!/bin/bash
# Copyright 2006 Sandia Corporation. Under the terms of Contract 
# DE-AC04-94AL85000, there is a non-exclusive license for use of this work 
# by or on behalf of the U.S. Government. Export of this program may require 
# a license from the United States Government.

#PBS -q regular
#PBS -V
#PBS -N overhead
#PBS -l mppwidth=48,walltime=0:30:00
cd $PBS_O_WORKDIR

mpirun="smpirun -npernode 1"
# mpirun="aprun -cc cpu -ss -N 1 -q"

min_msgsize=0
max_msgsize=`expr 4 \* 1024 \* 1024`
msgsize=$min_msgsize
while [ $msgsize -le $max_msgsize ]
do
  command="$mpirun -n 2 ./mpi_overhead --msgsize $msgsize $1"
  if [ $msgsize -gt $min_msgsize ]; then
    command="$command --nohdr"
  fi
  $command

  if [ $msgsize -eq 0 ]; then
    msgsize=2
  else
    msgsize=`expr $msgsize \* 2`
  fi
done
